import os

CONSUMER_KEY = os.getenv("CONSUMER_KEY", "YOUR CONSUMER KEY HERE")
CONSUMER_SECRET = os.getenv("CONSUMER_SECRET", "YOUR CONSUMER SECRET HERE")
ACCESS_TOKEN = os.getenv("ACCESS_TOKEN", "YOUR ACCESS_TOKEN HERE")
ACCESS_TOKEN_SECRET = os.getenv("ACCESS_TOKEN_SECRET", "YOUR ACCESS_TOKEN_SECRET HERE")
